theme: jekyll-theme-leap-day
title: A relevância e as aplicações da Bioinformática no cenário atual
description: Um pequeno repositório para armazenar o minicurso de Bioinformática ministrado durante a XX semabio.
