theme: ekyll-theme-leap-day
title: Minicurso de Bioinform치tica (XX SemaBio UnB)
description: Um pequeno reposit칩rio para armazenar os principais links do minicurso de Bioinform치tica ministrado durante a XX semabio de modo a deix치-los abertos e arquivados.
